# fly.toml app configuration file generated for onchain-fetcher on 2026-08-16T12:30:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onchain-fetcher'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  RESOLVE_INTERVAL = '15m'
  RPC_ENDPOINT_BASE = 'https://mainnet.base.org/'
  RPC_ENDPOINT_BSC = 'https://bsc-dataseed.nariox.org/'
  RPC_ENDPOINT_SOLANA = 'https://api.mainnet-beta.solana.com/'
  TOKEN_ORDER_CACHE = '/app/cache/token_order_cache.json'

[processes]
  app = '/app/watcher'
  resolver = '/app/resolver'

[[mounts]]
  source = 'fetcher_cache'
  destination = '/app/cache'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
